Repository teamdigitale/daf-nteract, pull requests merged in 2019-06, with the labels that each got.

#103 New publiccode.yml and AUTHORS files
  AUTHORS
  publiccode.yml
Labels: enhancement, help wanted

#105 Update LoginDialog buttons appeareance
  packages/pdnd-nteract-packages/login/package.json
  packages/pdnd-nteract-packages/login/src/LoginDialog.tsx
Labels: FrontEnd, enhancement

#106 Show "call-to-action" on Logout button
  packages/pdnd-nteract-packages/login/package.json
  packages/pdnd-nteract-packages/login/src/LoginLogoutButton.tsx
Labels: FrontEnd, enhancement

#107 Remove basic authentication token
  packages/epics/src/execute.ts
  packages/pdnd-nteract-packages/login/duck/loginDuck.ts
  packages/pdnd-nteract-packages/login/package.json
  packages/pdnd-nteract-packages/save-dataset/duck/saveDatasetDuck.ts
  packages/pdnd-nteract-packages/save-dataset/package.json
  packages/pdnd-nteract-packages/select-dataset/duck/selectedDatasetDuck.ts
  packages/pdnd-nteract-packages/select-dataset/package.json
Labels: enhancement

#109 Bugfix: Broken cells execution
  packages/epics/src/execute.ts
Labels: FrontEnd, bug
